project:
  type: website

website:
  title: "J. Tyler Kirby"
  navbar:
    right:
      - about.qmd
      - papers.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    css: styles.css



