---
title: "Papers and Talks"
about:
  template: solana
---
### Client Side Deep Learning Optimization with PyTorch

#### Presented at Strange Loop 2021
<iframe width="560" height="315" src="https://www.youtube.com/embed/s-CbBWKK5gk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Abstract**: Deep learning has the capacity to take in rich, high dimensional data and produce insights that can create totally new mobile experiences for developers. However, the constraints of network availability and latency limit what kinds of work can be done in the mobile application space and vastly increase the cost to developers. We have recently developed a customer facing mobile application that leverages real-time computer vision models and will share our experiences of moving multiple deep learning models from the server onto the client. In this presentation, we dive into technical solutions for porting custom architectures for various vision tasks and how to serialize them from Python to binary assets, while avoiding common issues such as unsupported hardware instructions. We also discuss the theory and practice of quantizing models, model fusion, and storing tensors in last memory format for optimization. We conclude by demonstrating how to benchmark the performance of client-side models for various devices and operating systems.

### Auceps syllabarum: A Digital Analysis of Latin Prose Rhythm

#### Published in the Journal of Roman Studies 2019



[Keeline, T., & Kirby, T. (2019). Auceps syllabarum: A Digital Analysis of Latin Prose Rhythm. Journal of Roman Studies, 109, 161-204. doi:10.1017/S0075435819000881](https://www.cambridge.org/core/journals/journal-of-roman-studies/article/abs/auceps-syllabarum-a-digital-analysis-of-latin-prose-rhythm/CA6F93A4BAC158FE9BAE05299A56F116)

**Abstract**: In this article we describe a series of computer algorithms that generate prose rhythm data for any digitised corpus of Latin texts. Using these algorithms, we present prose rhythm data for most major extant Latin prose authors from Cato the Elder through the second century A.D. Next we offer a new approach to determining the statistical significance of such data. We show that, while only some Latin authors adhere to the Ciceronian rhythmic canon, every Latin author is ‘rhythmical’ — they just choose different rhythms. Then we give answers to some particular questions based on our data and statistical approach, focusing on Cicero, Sallust, Tacitus and Pliny the Younger. In addition to providing comprehensive new data on Latin prose rhythm, presenting new results based on that data and confirming certain long-standing beliefs, we hope to make a contribution to a discussion of digital and statistical methodology in the study of Latin prose rhythm and in Classics more generally. The [Supplementary Material](https://doi.org/10.1017/S0075435819000881) available online contains an appendix with tables, data and code. This appendix constitutes a static ‘version of record’ for the data presented in this article, but we expect to continue to update our code and data; updates can be found in the repository of the [Classical Language Toolkit](https://github.com/cltk/cltk).